development:
   adapter: mysql2
   database: myblog_development
   username: root
   password: root
   host: localhost

test:
   adapter: mysql2
   database: pos2
   username: root
   password: root
   host: localhost

production:
   adapter: mysql2
   database: <%= ENV["DB_DATABASE"] %>
   username: <%= ENV["DB_USERNAME"] %>
   password: <%= ENV["DB_Password"] %>
   host: <%= ENV["DB_HOST"] %>
